require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['test/**/*_test.rb']
  t.verbose = true
end

desc "Pry console with preloaded model and api"
task :console do
  sh "bundle exec pry -I./lib -r model.rb -r api.rb"
end
